### ISSUE TITLE
undefined method `mount_base64_uploader' for #<Class:0x007f1f3055e8e8>

### ISSUE THREAD

**Issue by ArielAleksandrus** [lebedev-yury/carrierwave-base64#13]
I installed the gem "gem install 'carrierwave-base64'"
I included it to my Gemfile "gem 'carrierwave-base64'"
and changed the method mount_uploader to mount_base64_uploader.

I didn't change my previous uploader class:
    "class FotoUploader < CarrierWave::Uploader::Base
        .....
    end"

And I got this error message. How can I use carrierwave base64?

**Comment by ArielAleksandrus** [comment]
This is embarassing... I forgot to restart the server

**Comment by lebedev-yury** [comment]
no problems, it just happens :)

**Comment by jeremyeaton89** [comment]
Heyo, 

Hopefully i'm doing something stupid, but i've included this gem in my gemfile, bundle installed, and restarted server but i still get the same undefined method complaint.

**Comment by lebedev-yury** [comment]
@jeremyeaton89  try `bin/spring stop`, and restart your server

**Comment by dmmcgee** [comment]
I am also having this exact issue. bin/spring stop, and restarting my server did not fix it.

**Comment by lebedev-yury** [comment]
@dmmcgee thanks for reporting!

Is the `ApplicationRecord` inheriting from `ActiveRecord::Base`?

**Comment by lebedev-yury** [comment]
well, you can try to require Carrierwave ActiveRecord adapter explicitly in initializer:

```ruby
# config/initializers/carrierwave.rb
require 'carrierwave/orm/activerecord'
```

**Comment by guicattani** [comment]
I had a strange scenario where `mount_base64_uploader` wasn't being recognized as a method too. After a bit of poking around I got it to work by requiring the base64 class with `require 'carrierwave/base64'` on top of the model.
For some reason it wasn't loading correctly.

Cheers!
