### ISSUE TITLE
Multi file uploads

### ISSUE THREAD

**Issue by benwoodward** [lebedev-yury/carrierwave-base64#14]
I created a multi uploads method that corresponds to the ```mount_uploaders``` method in Carrierwave master, there are no tests because carrierwave-base64 doesn't use Carrierwave master. If you create a dev branch, maybe I could PR it to that?

https://github.com/benwoodward/carrierwave-base64/tree/multi-uploads

**Comment by lebedev-yury** [comment]
yep, sure

**Comment by lebedev-yury** [comment]
https://github.com/lebedev-yury/carrierwave-base64/tree/dev
