### ISSUE TITLE
Allow different filenames

### ISSUE THREAD

**Issue by lobo-tuerto** [lebedev-yury/carrierwave-base64#21]
Nevermind!

**Comment by lebedev-yury** [comment]
@lobo-tuerto: sorry for a long response

if this is still a problem, you might want to customize the upload path, which you can do in an uploader file

**Comment by lobo-tuerto** [comment]
Thank you @lebedev-yury, I asked the question before reading your code. After the reading I realized that the way to achieve that was to modify my uploader class, like this:

```ruby
def filename
  model.nombre_archivo if original_filename
end
```

All is good, sorry for the troubles!

**Comment by lebedev-yury** [comment]
ok, no problem :)
