### ISSUE TITLE
Should setting an image to empty string remove it?

### ISSUE THREAD

**Issue by jmuheim** [lebedev-yury/carrierwave-base64#22]
Just a simple question: Should setting an image to empty string remove it? Or can it only be removed using Carrierwave's `remove_xxx` field?

**Comment by lebedev-yury** [comment]
it can be only removed by using `remove_xxx`, there's a `present?` check for the new value in the `adapter.rb`

**Comment by jmuheim** [comment]
Thanks!

**Comment by lebedev-yury** [comment]
You're welcome!
