### ISSUE TITLE
Element is always marked as changed, also if it's not

### ISSUE THREAD

**Issue by jmuheim** [lebedev-yury/carrierwave-base64#23]
I just noticed that an element that has a `mount_base64_uploader` mounted is always marked as changed and thus saved to the DB, even when it's not changed.

It's a bit hard to describe, but let's try this.

I have a `User` model like this:

```ruby
class User < ActiveRecord::Base
  mount_base64_uploader :file_upload,   ImageUploader
  mount_base64_uploader :string_upload, ImageUploader
end
```

When I edit it in a form and **don't** change a thing, then the following DB query is executed anyways due to the log file:

```
  SQL (0.3ms)  UPDATE "users" SET "string_upload" = ?, "updated_at" = ? WHERE "users"."id" = ?  [["string_upload", "file.png"], ["updated_at", "2015-10-19 15:27:10.106767"], ["id", 10]]
```

Here are the `user_params`:

```
$ user_params
=> {"name"=>"2haha",
 "file_upload_cache"=>"",
 "remove_file_upload"=>"0",
 "string_upload"=>"file.png",
 "string_upload_cache"=>"",
 "remove_string_upload"=>"0"
}
```

Notice: only the `:string_upload` field is written to DB, not the `:file_upload`, so I guess it's a problem in your gem. I think you have to check whether the sent param is only `file.png` and then you **don't** mark the attribute as changed.

While this may not be a big issue, it breaks some custom functionality of my app that relies on the fact that resources announce their changed status correctly.

You can still checkout my demo app here to see the problematic behaviour: https://github.com/jmuheim/test-carrierwave-base64-update

**Comment by jmuheim** [comment]
Investigating the issue a little further gave the following result:

When there is a file already available for `:string_upload`, then the textarea field has the content `file.png`.

- When submitting it with this value, then an UPDATE is triggered.
- When submitting it empty, no UPDATE is triggered.

Is this a problem on the form's side now or on your side?

I generally think your gem should be a little more picky about the submitted values: only a valid base64 string or an empty value should be treated as valid; others should add a validation error like `invalid format` or so.

**Comment by jmuheim** [comment]
For the time being, I simply do `f.input :string_upload, as: :text, value: nil`, which does the trick. Yet, I think it's not really the solution to the named problem.

**Comment by lebedev-yury** [comment]
Sorry, haven't got a time to look at it. Will try to do it on this week

**Comment by jmuheim** [comment]
Seems that my workaround with setting value to nil breaks the possibility to remove the file with carrierwave's `remove_xxx` checkbox input.

Thanks for looking into it.

**Comment by lebedev-yury** [comment]
After taking a closer look at the problem you described, here is what i think:

Showing the persisted file name in a base64 text input field makes no sense, since it is not a base64 encoded image data. Setting the input value is the most correct way i can think of to deal with the problem you have.

The functionality with removing stored uploads should not be broken by the nil value for the input field. Maybe it is something more app specific? If you could provide me some details on the error, i would be glad to help.

I also added a spec for uploads removing functionality:
https://github.com/lebedev-yury/carrierwave-base64/blob/master/spec/adapter_spec.rb#L46

**Comment by jmuheim** [comment]
Thanks for helping. I will take another look at my app next week and provide you with details, if necessary.

Have a nice weekend! :)

**Comment by lebedev-yury** [comment]
thanks, you too :)

**Comment by lebedev-yury** [comment]
@jmuheim: I will close this issue for now, if you still have problems with that, just open it again
