### ISSUE TITLE
Not keeping file name

### ISSUE THREAD

**Issue by mchicote** [lebedev-yury/carrierwave-base64#24]
Hi
On https://github.com/lebedev-yury/carrierwave-base64/blob/master/lib/carrierwave/base64/base64_string_io.rb#L21 the original file name is not taken into consideration. Is it possible to keep the file name?

Thanks

**Comment by lebedev-yury** [comment]
Hi!

For regular file uploads the file name should be kept. For base64 strings there is no filename basically, therefor it is set to `file.extension`

**Comment by mchicote** [comment]
ohh too bad
So if I want to change the filename I would have to do it manually after the file is uploaded?

thanks!

**Comment by lebedev-yury** [comment]
yep, you need to override the `original_filename` method, or you could change the store path

you're welcome!
