### ISSUE TITLE
Uploading broken files to Amazon S3

### ISSUE THREAD

**Issue by Mohakjuneja** [lebedev-yury/carrierwave-base64#31]
I'm using mongoid along with carrierwave to upload files using JSON API. My controller method looks like this-

```
def create
    content = Content.new(content_params)     
    content.user_id = current_user.id 
    content.asset_type = content.asset.file.extension      
    if content.save      
      render json: content, status: 201, location: [:api, content] 
      ProcessAsset.perform_async(content.id.to_s) unless content.asset_type != 'pdf'
    else
      render json: { errors: content.errors }, status: 422
    end
end

```
Model

```
class Content

  include Mongoid::Document
  include Mongoid::Timestamps

  before_create :set_base_price

  mount_base64_uploader :asset, AssetUploader
  # more code
end


```
While the whole process works great, the file uploaded to S3 (pdf in this case) has no content in it.
I believe this has something to do with StringIO being used to read the file from the system. It sets the content_type to plain/text. This is confirmed when I download the pdf and try to open it on my system.

Here's my json I'm using to upload - 
{
            "content": {
                    "campus" : "569df3c4be84c511c0000001",
                    "course" : "569dfe1cbe84c511c0000006",
                    "subject" : "56a0c4debe84c50d2f000006",
                    "batch" : "2015",
                    "title" : "RipAndSave",
                    "asset": "data:application/pdf;base64,L2hvbWUvbW9qby9Eb3dubG9hZHMvc2FtcGxlLnBkZg=="
                }
            }

I'm using Rails 4.2, Mongoid 5.1

Can you help?

**Comment by Mohakjuneja** [comment]
@lebedev-yury Have you been able to take a look at this yet?

**Comment by lebedev-yury** [comment]
Hi! You are experiencing the problem only with pdf file uploads, or with other file types too?

**Comment by Mohakjuneja** [comment]
It's the same for images too. The content type saved is text/html

**Comment by lebedev-yury** [comment]
You mean that when you open the url to the uploaded file, it shows the file as plain in the browser? If yes, this might be a problem with incorrect content-disposition, set in your amazon s3

**Comment by Mohakjuneja** [comment]
Hey Yuri,
I'm publishing a sample repository for the above error. The storage, both file system and remote (S3) set the content type to text/plain. You can fork the repository to test it. Also, I don't set content-disposition anywhere.

[https://github.com/Mohakjuneja/Base64upload](url)

**Comment by lebedev-yury** [comment]
> The base64 string when decoded is the absolute path to the original file on local machine.

I think you misunderstand the concept of base64 encoded uploads. How do you think your web application would get the file contents from your local machine, by just having the address?

Base64 string should contain the contents of the file, that you want to upload, encoded in base64 string

**Comment by Mohakjuneja** [comment]
Hi Yuri,
I apologise. I figured it myself just a few hours after writing to you. I'm
sorry about the trouble. I was fixated on it for over a week when I wrote
to you. Thank you for taking out time to see it!

**Comment by Mohakjuneja** [comment]
Hi @lebedev-yury ,
I'm trying to upload multiple files(20), with an average size of 700 KB using careerwave-base64 but my request times out. Is it suitable to upload them with this approach?
