### ISSUE TITLE
Not compatible with latest carrierwave

### ISSUE THREAD

**Issue by sachin87** [lebedev-yury/carrierwave-base64#39]
I have latest `carrierwave` gem installed in my `rails 5` app and I am getting this error message while doing `bundle`.Please Help.
```

Bundler could not find compatible versions for gem "carrierwave":
  In snapshot (Gemfile.lock):
    carrierwave (= 1.0.0.beta)

  In Gemfile:
    carrierwave (< 2.0, >= 1.0.0.beta)

    carrierwave-base64 was resolved to 2.3.1, which depends on
      carrierwave (< 0.12.0, >= 0.8.0)

Running `bundle update` will rebuild your snapshot from scratch, using only
the gems in your Gemfile, which may resolve the conflict.
```

**Comment by Rubioli** [comment]
Instead of using **gem 'carrierwave', '>= 1.0.0.beta', '< 2.0'**, just comment it out and add this **gem 'carrierwave', '~> 0.11.2'**

Run `bundle install`, when it installed **gem 'carrierwave', '~> 0.11.2'**, THEN add **gem 'carrierwave-base64'** and run `bundle install` again.

**Comment by lebedev-yury** [comment]
@Rubioli thanks! I will also release a new version in the next days.
