### ISSUE TITLE
Symbolic Link Error when trying to install on Windows

### ISSUE THREAD

**Issue by jzhang172** [lebedev-yury/carrierwave-base64#43]
https://i.stack.imgur.com/md96I.png

On my project that has carrierwave-base64 as a gem install...when I do bundle install, I get this error.  This looks like not necessary to be there?  Any idea how to bypass this error?

I am using Windows.  I don't get the error on Mac or Linux.

**Comment by lebedev-yury** [comment]
@jzhang172: thank you for reporting, I will fix this issue tomorrow

**Comment by lebedev-yury** [comment]
@jzhang172 this issue is fixed in the new version
