### ISSUE TITLE
Handle extensions from mime-type

### ISSUE THREAD

**Issue by Quintasan** [lebedev-yury/carrierwave-base64#47]
With #46 closed you can upload file which mime-types don't necessarily reflect their extension. The question now is how to handle those files. The current logic goes like this:

1. User uploads a base64 encoded docx file which has the mime-type of `application/vnd.openxmlformats-officedocument.wordprocessingml.document`
2. carrierwave-base64 names the file `file.extension` where `extension` is the part occuring after the `appliction/` in mime-type.
3. That will result in a file named `file.vnd.openxmlformats-officedocument.wordprocessingml.document` which will definitely fail the whitelisting rule in case one writes `docx` there instead of `vnd.openxmlformats-officedocument.wordprocessingml.document`

This is hardly user-friendly. How do we fix this?

**Comment by adamcrown** [comment]
I'd like to see a solution to this too. Currently I'm having to inject a bogus `application/extension` content type into my base64 string just to get the extension I want.

I'd think something like this as an alternative would make sense as a default with an option to override it maybe.

```ruby
MIME::Types['application/vnd.openxmlformats-officedocument.wordprocessingml.document'].first.preferred_extension
```

**Comment by Quintasan** [comment]
@adamcrown Thanks for looking into that. I'll try to take a stab at it this weekend.

**Comment by lebedev-yury** [comment]
How about passing a name of the file in the payload with the upload?

**Comment by Quintasan** [comment]
This would imply that you trust the person uploading the file to provide
you the right extension.

**Comment by lebedev-yury** [comment]
Then I think we should use [ruby-mime-types](https://github.com/mime-types/ruby-mime-types/) gem for that, since you can register the mime types you need in your application, and the mime type object has `preferred_extension` method, that we could use.

**Comment by lebedev-yury** [comment]
@Quintasan @adamcrown I made a commit, that adds automatic identification of the file extension, using the content type from the uploaded base64 string: c93c69000f18b2a4877144ba036fea449134058a.

If you have time, I would like you to test it. If it's fine, I will release a 2.3.5 version, including this change.

**Comment by lebedev-yury** [comment]
Ok, I think I can already release the 2.4.0

**Comment by adamcrown** [comment]
@lebedev-yury Sorry I'm so very late to this. I've just now had time to revisit this issue. Just wanted to let you know that it's working great. Thanks.

If anybody else stumbles on this and wonders how to add custom mime types. The documentation isn't great for the mime-types gem, but this is what worked for me

```ruby
MIME::Types.add(
  MIME::Type.new('application/icml').tap {
    |type| type.add_extensions 'icml'
  }
)
```

**Comment by lebedev-yury** [comment]
@adamcrown thank you! I will add this information to the readme
