### ISSUE TITLE
unknown mimetype data:image/jpg

### ISSUE THREAD

**Issue by knutigro** [lebedev-yury/carrierwave-base64#52]
Hi, after upgrading from 2.3.4 to 2.4.0 i started getting this error: `unknown mimetype data:image/jpg`

I use the following format when uploading my base64 string: `data:image/jpeg;base64,(base64 encoded data)`

My current fix is to revert to 2.3.4. again but I wonder if there has been some changes in api or if this is a bug?

/Knut

**Comment by lebedev-yury** [comment]
it's not a bug, officially the mimetype should be `data:image/jpeg`, which is also correct in your second sentence

**Comment by knutigro** [comment]
ah ok so as I understand it its the  `jpeg` vs `jpg` that is causing my problem. Thank you for the clarification.
