### ISSUE TITLE
Unknown MIME type! Can you tell me how to solve this issue? 

### ISSUE THREAD

**Issue by BranLiang** [lebedev-yury/carrierwave-base64#54]
Carrierwave::Base64::Base64StringIO::ArgumentError (Unknown MIME type: data:image/jpg):

I know you said using MIME::Types#add. But how? Thanks 
I am using Rails 5.1 and was trying to upload a image using curl.

(echo -n '{"data":{"cover": "data:image/jpg;base64,'; \
  base64 app/images/cover.jpg; echo '"}}') |
curl -X PATCH -H "Content-Type: application/json" -d @- \
  http://localhost:3000/api/books/45

**Comment by BranLiang** [comment]
white list defined in uploader
def extension_whitelist
    %w(jpg jpeg png)
  end

**Comment by lebedev-yury** [comment]
@BranLiang an easy fix would be to use `data:image/jpeg` mime type (with `e`)

For adding a mime type, you need to write an initializer

**Comment by BranLiang** [comment]
@lebedev-yury thanks, that works :dancing_men:

**Comment by lebedev-yury** [comment]
You're welcome!
