### ISSUE TITLE
Avatar is not saving into database

### ISSUE THREAD

**Issue by akshay-cs-borade** [lebedev-yury/carrierwave-base64#61]
Here, I'm using latest version of `carrierwave-base64` with `Rails 5.0.2`. Image is uploading into `/public/uploads/tmp` but saving nil avatar in database. Please have a look on this issue and do the needfull.

Thanks!

**Comment by lebedev-yury** [comment]
@akshay-cs-borade if you want me to investigate this issue, I would need more information from you regarding the issue. Can you at least post the code in your controller action that is responsible for saving the record, and the model code?
