### ISSUE TITLE
Support for multiple uploads ?

### ISSUE THREAD

**Issue by miguejs** [lebedev-yury/carrierwave-base64#66]
something like `mount_base64_uploaders`

**Comment by lebedev-yury** [comment]
is there really a need for that?

why would you want to send multiple files in one request via the API?

IMO if you make several API requests per file, it's much more convenient to track progress, retry them etc.

Or I am missing something?

**Comment by woohoou** [comment]
It could be a nice feature, carrierwave have the mount_uploaders feature.

**Comment by andrepcg** [comment]
I would also think this feature would be pretty nice

**Comment by woohoou** [comment]
@andrepcg I did a fork time ago, probably you can use the code.
