### ISSUE TITLE
issue with cloudinary gem integration

### ISSUE THREAD

**Issue by maceonrails** [lebedev-yury/carrierwave-base64#71]
Hi Guys, is it compatible with cloudinary integration? because when i change implementation from file storage to cloudinary base it doesn't work, but if i use default carrierwave gem it work.

**Comment by lebedev-yury** [comment]
Hi @maceonrails!

Currently there is no support for cloudinary integration. I can investigate a problem, if you will create a dummy application, that reproduces the described bug.
