### ISSUE TITLE
Is there any support for mongoid

### ISSUE THREAD

**Issue by aligit** [lebedev-yury/carrierwave-base64#9]
Hello and thanks for this nice gem
I was wondering if anything other than active record is supported? If not is there any interest that I create one for mongoid?

Best,
Ali

**Comment by lebedev-yury** [comment]
Thank you!

Mongoid is currently not supported, but i think it wouldn't be too complicated to add the support.

Do you want to do a pull request for this feature?

**Comment by aligit** [comment]
You are welcome

I'm working on that and if feasible and ready I'll send the pull request. What would essentially be required?

**Comment by lebedev-yury** [comment]
There is actually a pull request already for this issue:

https://github.com/lebedev-yury/carrierwave-base64/pull/10

**Comment by lebedev-yury** [comment]
296e1e77c93bb8b14598c185704e8e7144ca8748
